# smart meter puls counter version 1.0 - initial release for the youtube video 
esphome:
  name: smartmeter-pulscounter
  friendly_name: smartmeter_pulscounter

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "YOUR KEY"
# Please Use the Key which ESP Home automatically provided
# bitte nutzt den Key, der nach der Erstellung der ESP Home Instanz bei euch von Home Assistant eingetragen worden ist. 

ota:
  password: "yourOTAPW"
# Please Use the OTA PWD which ESP Home automatically provided
# bitte nutzt den OTA PWD, der nach der Erstellung der ESP Home Instanz bei euch von Home Assistant eingetragen worden ist. 


wifi:
  ssid: "secret wifi_ssid"
  password: "secret wifi_password"
  
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Smartmeter-Pulscounter"
    password: "APPassword644563245"

captive_portal:

sensor:
  - platform: pulse_counter
    pin: D1
# if you use a D1 Mini ESP8266 this is a good pin, otherwise D7 could work
# wenn du ein D1 Mini nutzt, ist D1 ein guter Pin, alternativ D7. 
    unit_of_measurement: 'kW'
    device_class: "power"
    state_class: "measurement"
    update_interval: 10s
    accuracy_decimals: 3
    name: 'smartmeter-power'
    id: myelectricity

    total:
      accuracy_decimals: 4
      unit_of_measurement: 'kWh'
      device_class: "energy"
      name: 'smartmeter-energy'
      filters:
        - multiply: 0.0001  # (1/10000 pulses per kWh)    

    
